version: '2'
services:
  # 共有ボリューム
  shared_volume:
    build: ./shared_volume
    tty: true
    volumes:
      - /var/run/php-fpm/
      - ../src:/src
  # API Blueprint
  api_blueprint:
    build: ./api_blueprint
    ports:
      - "8088:8088"
      - "3000:3000"
    volumes_from:
      - shared_volume
  # アプリケーション(Phalcon)
  app:
    build: ./app
    volumes_from:
      - shared_volume
    depends_on:
      - db
  # WEBサーバ(Nginx)
  web:
    build: ./web
    ports:
      - "80:80"
    volumes_from:
      - shared_volume
  # DBサーバ(MySQL)
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpass
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
