version: '2'
services:
  api_blueprint:
    build: ./api_blueprint
    ports:
      - "8088:8088"
      - "3000:3000"
    volumes:
      - ../src/api_blueprint:/usr/src/api_blueprint/src
  app:
    build: ./app
    volumes:
      - /var/run/php-fpm/
      - ../src:/var/www/html
  web:
    build: ./web
    ports:
      - "80:80"
    volumes_from:
      - app
    


